### ISSUE TITLE
默认浏览器设置

### ISSUE THREAD

**Issue by chenwenbo** [shuson/wox-plugin-zhihudaily#1]
是不是使用默认浏览器打开网页会比较好？  我查看您的源码的时候发现写死了浏览器的路径..

**Comment by shuson** [comment]
情况是这样的：我故意的。lol
我在自己电脑上没把chrome设置成默认浏览器，是为了让很多公司内部的链接还用ie打开，因为ie和chrome我用了不同的proxy设置。
现在更新了一下插件，已经把chrome打开的code拿掉了
